import json

notebook_path = r"C:\Users\EV-Car\Main_Project.ipynb"

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

afm_cells = [
    {
        "cell_type": "markdown",
        "id": "afm-header",
        "metadata": {},
        "source": [
            "# Adaptive Fusion Model (AFM) for Small-Sample Regime\n",
            "\n",
            "The Gated Fusion Network (~106 parameters on ~20 samples) risks collapsing to\n",
            "majority-class prediction. We propose a **minimal-parameter Adaptive Fusion Model**:\n",
            "\n",
            "- **Fusion**: $x_t = \\alpha \\cdot S_t + (1-\\alpha) \\cdot F_t$ with learned $\\alpha \\in [0,1]$\n",
            "- **Classification**: L2-regularised logistic regression (Gaussian prior interpretation)\n",
            "- **Evaluation**: Nested LOOCV \u2014 inner loop selects $\\alpha^*$, outer loop evaluates\n",
            "- **Total parameters**: 3 ($\\alpha$, $w$, $b$) vs ~106 for GFN\n",
            "\n",
            "$\\alpha$ directly measures the relative predictive contribution of sentiment vs fundamentals,\n",
            "consistent with Granger causality validation."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "afm-landscape",
        "metadata": {},
        "outputs": [],
        "source": [
            'X_sent_raw = final_df[["Annual_Sentiment_Norm"]].values\n',
            'X_fund_raw = final_df[["Fundamental_Score_FF"]].values\n',
            'y_afm = final_df["market_up_next"].values\n',
            '\n',
            'from sklearn.linear_model import LogisticRegression\n',
            '\n',
            'alphas = np.linspace(0, 1, 101)\n',
            'alpha_accs = []\n',
            '\n',
            'for alpha in alphas:\n',
            '    loo = LeaveOneOut()\n',
            '    fold_preds = []\n',
            '    for tr_idx, te_idx in loo.split(X_sent_raw):\n',
            '        imp_s, sc_s = SimpleImputer(strategy="median"), StandardScaler()\n',
            '        imp_f, sc_f = SimpleImputer(strategy="median"), StandardScaler()\n',
            '        Xs_tr = sc_s.fit_transform(imp_s.fit_transform(X_sent_raw[tr_idx]))\n',
            '        Xs_te = sc_s.transform(imp_s.transform(X_sent_raw[te_idx]))\n',
            '        Xf_tr = sc_f.fit_transform(imp_f.fit_transform(X_fund_raw[tr_idx]))\n',
            '        Xf_te = sc_f.transform(imp_f.transform(X_fund_raw[te_idx]))\n',
            '        X_tr = alpha * Xs_tr + (1 - alpha) * Xf_tr\n',
            '        X_te = alpha * Xs_te + (1 - alpha) * Xf_te\n',
            '        clf = LogisticRegression(C=1.0, penalty="l2", solver="lbfgs", max_iter=1000, random_state=42)\n',
            '        clf.fit(X_tr, y_afm[tr_idx])\n',
            '        fold_preds.append(clf.predict(X_te)[0])\n',
            '    alpha_accs.append(accuracy_score(y_afm, fold_preds))\n',
            '\n',
            'best_simple_alpha = alphas[np.argmax(alpha_accs)]\n',
            'best_simple_acc = max(alpha_accs)\n',
            'baseline_afm = max(np.mean(y_afm), 1 - np.mean(y_afm))\n',
            '\n',
            'print("Alpha Landscape Results:")\n',
            'print(f"  Best alpha: {best_simple_alpha:.2f}")\n',
            'print(f"  Best LOOCV accuracy: {best_simple_acc:.4f}")\n',
            'print(f"  Baseline (majority): {baseline_afm:.4f}")\n',
            'print(f"  vs Baseline: {best_simple_acc - baseline_afm:+.4f}")'
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "afm-nested-loocv",
        "metadata": {},
        "outputs": [],
        "source": [
            'loo_outer = LeaveOneOut()\n',
            'afm_preds, afm_actuals, afm_fold_alphas = [], [], []\n',
            'alpha_grid = np.linspace(0, 1, 21)\n',
            '\n',
            'for out_tr, out_te in loo_outer.split(X_sent_raw):\n',
            '    best_inner_alpha, best_inner_acc = 0.5, -1\n',
            '    for alpha in alpha_grid:\n',
            '        loo_inner = LeaveOneOut()\n',
            '        inner_preds = []\n',
            '        for in_tr, in_te in loo_inner.split(X_sent_raw[out_tr]):\n',
            '            actual_tr = out_tr[in_tr]\n',
            '            actual_te = out_tr[in_te]\n',
            '            imp_s, sc_s = SimpleImputer(strategy="median"), StandardScaler()\n',
            '            imp_f, sc_f = SimpleImputer(strategy="median"), StandardScaler()\n',
            '            Xs_tr = sc_s.fit_transform(imp_s.fit_transform(X_sent_raw[actual_tr]))\n',
            '            Xs_te = sc_s.transform(imp_s.transform(X_sent_raw[actual_te]))\n',
            '            Xf_tr = sc_f.fit_transform(imp_f.fit_transform(X_fund_raw[actual_tr]))\n',
            '            Xf_te = sc_f.transform(imp_f.transform(X_fund_raw[actual_te]))\n',
            '            X_tr = alpha * Xs_tr + (1 - alpha) * Xf_tr\n',
            '            X_te = alpha * Xs_te + (1 - alpha) * Xf_te\n',
            '            clf = LogisticRegression(C=1.0, penalty="l2", solver="lbfgs", max_iter=1000, random_state=42)\n',
            '            clf.fit(X_tr, y_afm[actual_tr])\n',
            '            inner_preds.append(clf.predict(X_te)[0])\n',
            '        inner_acc = accuracy_score(y_afm[out_tr], inner_preds)\n',
            '        if inner_acc > best_inner_acc:\n',
            '            best_inner_acc = inner_acc\n',
            '            best_inner_alpha = alpha\n',
            '\n',
            '    imp_s, sc_s = SimpleImputer(strategy="median"), StandardScaler()\n',
            '    imp_f, sc_f = SimpleImputer(strategy="median"), StandardScaler()\n',
            '    Xs_tr = sc_s.fit_transform(imp_s.fit_transform(X_sent_raw[out_tr]))\n',
            '    Xs_te = sc_s.transform(imp_s.transform(X_sent_raw[out_te]))\n',
            '    Xf_tr = sc_f.fit_transform(imp_f.fit_transform(X_fund_raw[out_tr]))\n',
            '    Xf_te = sc_f.transform(imp_f.transform(X_fund_raw[out_te]))\n',
            '    X_tr = best_inner_alpha * Xs_tr + (1 - best_inner_alpha) * Xf_tr\n',
            '    X_te = best_inner_alpha * Xs_te + (1 - best_inner_alpha) * Xf_te\n',
            '    clf = LogisticRegression(C=1.0, penalty="l2", solver="lbfgs", max_iter=1000, random_state=42)\n',
            '    clf.fit(X_tr, y_afm[out_tr])\n',
            '    afm_preds.append(clf.predict(X_te)[0])\n',
            '    afm_actuals.append(y_afm[out_te[0]])\n',
            '    afm_fold_alphas.append(best_inner_alpha)\n',
            '\n',
            'afm_acc = accuracy_score(afm_actuals, afm_preds)\n',
            'afm_prec = precision_score(afm_actuals, afm_preds, zero_division=0)\n',
            'afm_rec = recall_score(afm_actuals, afm_preds, zero_division=0)\n',
            'afm_f1 = f1_score(afm_actuals, afm_preds, zero_division=0)\n',
            '\n',
            'print("=" * 60)\n',
            'print("ADAPTIVE FUSION MODEL - NESTED LOOCV RESULTS")\n',
            'print("=" * 60)\n',
            'print(f"Accuracy  : {afm_acc:.4f}")\n',
            'print(f"Precision : {afm_prec:.4f}")\n',
            'print(f"Recall    : {afm_rec:.4f}")\n',
            'print(f"F1 Score  : {afm_f1:.4f}")\n',
            'print(f"Baseline  : {baseline_afm:.4f}")\n',
            'print(f"vs Base   : {afm_acc - baseline_afm:+.4f}")\n',
            'print(f"\\nPer-fold alpha: mean={np.mean(afm_fold_alphas):.3f}  std={np.std(afm_fold_alphas):.3f}")\n',
            'print(f"Alpha range: [{np.min(afm_fold_alphas):.2f}, {np.max(afm_fold_alphas):.2f}]")'
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "afm-viz",
        "metadata": {},
        "outputs": [],
        "source": [
            'fig, axes = plt.subplots(2, 2, figsize=(14, 10))\n',
            '\n',
            'axes[0, 0].plot(alphas, alpha_accs, color="#2c3e50", linewidth=2)\n',
            'axes[0, 0].axhline(y=baseline_afm, color="red", linestyle="--", label=f"Baseline ({baseline_afm:.3f})")\n',
            'axes[0, 0].axvline(x=best_simple_alpha, color="green", linestyle=":", alpha=0.7,\n',
            '                    label=f"Best alpha={best_simple_alpha:.2f}")\n',
            'axes[0, 0].fill_between(alphas, alpha_accs, alpha=0.1, color="#3498db")\n',
            'axes[0, 0].set_xlabel("alpha (Sentiment Weight)")\n',
            'axes[0, 0].set_ylabel("LOOCV Accuracy")\n',
            'axes[0, 0].set_title("Fusion Weight Landscape\\nalpha=0: pure fundamental | alpha=1: pure sentiment")\n',
            'axes[0, 0].legend(fontsize=9)\n',
            'axes[0, 0].set_xlim(0, 1)\n',
            '\n',
            'fold_colors = ["#e74c3c" if a > 0.5 else "#3498db" for a in afm_fold_alphas]\n',
            'axes[0, 1].bar(range(len(afm_fold_alphas)), afm_fold_alphas, color=fold_colors, alpha=0.85, edgecolor="white")\n',
            'axes[0, 1].axhline(y=0.5, color="black", linestyle="--", linewidth=1)\n',
            'axes[0, 1].axhline(y=np.mean(afm_fold_alphas), color="green", linestyle="-", linewidth=1.5,\n',
            '                    label=f"Mean alpha={np.mean(afm_fold_alphas):.3f}")\n',
            'axes[0, 1].set_xlabel("LOOCV Fold")\n',
            'axes[0, 1].set_ylabel("Selected alpha*")\n',
            'axes[0, 1].set_title("Per-Fold Optimal Fusion Weight\\n(red=sentiment, blue=fundamental)")\n',
            'axes[0, 1].set_ylim(0, 1)\n',
            'axes[0, 1].legend(fontsize=9)\n',
            '\n',
            'cm_afm = confusion_matrix(afm_actuals, afm_preds)\n',
            'sns.heatmap(cm_afm, annot=True, fmt="d", cmap="Greens",\n',
            '            xticklabels=["Down", "Up"], yticklabels=["Down", "Up"], ax=axes[1, 0])\n',
            'axes[1, 0].set_xlabel("Predicted")\n',
            'axes[1, 0].set_ylabel("Actual")\n',
            'axes[1, 0].set_title(f"AFM Confusion Matrix (Acc={afm_acc:.3f})")\n',
            '\n',
            'models_all = ["Majority\\nBaseline", "Gradient\\nBoosting", "Gated Fusion\\nNet", "Adaptive\\nFusion"]\n',
            'accs_all = [baseline_afm, gb_acc, gfn_acc, afm_acc]\n',
            'colors_all = ["#95a5a6", "#3498db", "#e74c3c", "#2ecc71"]\n',
            'bars = axes[1, 1].bar(models_all, accs_all, color=colors_all, edgecolor="white", width=0.6)\n',
            'for bar, acc in zip(bars, accs_all):\n',
            '    axes[1, 1].text(bar.get_x() + bar.get_width()/2, acc + 0.01, f"{acc:.3f}",\n',
            '                     ha="center", fontsize=10, fontweight="bold")\n',
            'axes[1, 1].set_ylabel("LOOCV Accuracy")\n',
            'axes[1, 1].set_title("All Models Comparison")\n',
            'axes[1, 1].set_ylim(0, 1.1)\n',
            '\n',
            'plt.suptitle("Adaptive Fusion Model - Results", fontsize=14, fontweight="bold")\n',
            'plt.tight_layout()\n',
            'plt.savefig(r"C:\\Users\\EV-Car\\Downloads\\afm_results.png", dpi=300)\n',
            'plt.show()'
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "id": "afm-summary",
        "metadata": {},
        "outputs": [],
        "source": [
            'full_comparison = pd.DataFrame([\n',
            '    {"Model": "Majority Baseline", "Accuracy": baseline_afm, "Precision": "-", "Recall": "-", "F1": "-", "Params": 0, "vs Baseline": 0.0},\n',
            '    {"Model": "Gradient Boosting", "Accuracy": gb_acc, "Precision": gb_prec, "Recall": gb_rec, "F1": gb_f1, "Params": "100+", "vs Baseline": gb_acc - baseline_afm},\n',
            '    {"Model": "Gated Fusion Net", "Accuracy": gfn_acc, "Precision": gfn_prec, "Recall": gfn_rec, "F1": gfn_f1, "Params": "~106", "vs Baseline": gfn_acc - baseline_afm},\n',
            '    {"Model": "Adaptive Fusion", "Accuracy": afm_acc, "Precision": afm_prec, "Recall": afm_rec, "F1": afm_f1, "Params": 3, "vs Baseline": afm_acc - baseline_afm},\n',
            '])\n',
            '\n',
            'print("=" * 90)\n',
            'print("FULL MODEL COMPARISON")\n',
            'print("=" * 90)\n',
            'print(full_comparison.to_string(index=False))\n',
            'print()\n',
            'mean_alpha = np.mean(afm_fold_alphas)\n',
            'print(f"AFM mean fusion weight alpha = {mean_alpha:.3f}")\n',
            'if mean_alpha > 0.5:\n',
            '    print(f"  Sentiment contributes {mean_alpha:.0%} vs Fundamentals {1-mean_alpha:.0%}")\n',
            'else:\n',
            '    print(f"  Fundamentals contribute {1-mean_alpha:.0%} vs Sentiment {mean_alpha:.0%}")\n',
            'print(f"  Alpha stability (std): {np.std(afm_fold_alphas):.3f}")\n',
            'print()\n',
            'print("Why AFM suits this regime:")\n',
            'print("  1. Only 3 parameters vs 100+ for GFN - prevents overfitting on ~20 samples")\n',
            'print("  2. Nested LOOCV ensures no leakage in fusion weight selection")\n',
            'print("  3. Alpha is directly interpretable as modality importance")\n',
            'print("  4. Consistent with Granger causality: combined signal > sentiment alone")\n',
            '\n',
            'full_comparison.to_csv(r"C:\\Users\\EV-Car\\Downloads\\full_model_comparison.csv", index=False)\n',
            'print("\\nResults saved to Downloads/full_model_comparison.csv")'
        ]
    }
]

nb["cells"].extend(afm_cells)

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print("Done! 5 AFM cells added to the end of Main_Project.ipynb")
print("Now re-run the entire notebook from top to bottom.")
